# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Australia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('body_1', models.TextField()),
                ('body_2', models.TextField()),
                ('title_img', models.ImageField(upload_to='images/')),
                ('img_1', models.ImageField(upload_to='images/')),
                ('img_2', models.ImageField(upload_to='images/')),
                ('img_3', models.ImageField(blank=True, upload_to='images/')),
                ('img_4', models.ImageField(blank=True, upload_to='images/')),
                ('Date_of_Publishing', models.DateField()),
                ('Author', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='England',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('body_1', models.TextField()),
                ('body_2', models.TextField()),
                ('title_img', models.ImageField(upload_to='images/')),
                ('img_1', models.ImageField(upload_to='images/')),
                ('img_2', models.ImageField(upload_to='images/')),
                ('img_3', models.ImageField(blank=True, upload_to='images/')),
                ('img_4', models.ImageField(blank=True, upload_to='images/')),
                ('Date_of_Publishing', models.DateField()),
                ('Author', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='india',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('body_1', models.TextField()),
                ('body_2', models.TextField()),
                ('title_img', models.ImageField(upload_to='images/')),
                ('img_1', models.ImageField(upload_to='images/')),
                ('img_2', models.ImageField(upload_to='images/')),
                ('img_3', models.ImageField(blank=True, upload_to='images/')),
                ('img_4', models.ImageField(blank=True, upload_to='images/')),
                ('Date_of_Publishing', models.DateField()),
                ('Author', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='South_Africa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('body_1', models.TextField()),
                ('body_2', models.TextField()),
                ('title_img', models.ImageField(upload_to='images/')),
                ('img_1', models.ImageField(upload_to='images/')),
                ('img_2', models.ImageField(upload_to='images/')),
                ('img_3', models.ImageField(blank=True, upload_to='images/')),
                ('img_4', models.ImageField(blank=True, upload_to='images/')),
                ('Date_of_Publishing', models.DateField()),
                ('Author', models.CharField(max_length=50)),
            ],
        ),
    ]
