# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 03:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cric', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Australia',
            new_name='Aus',
        ),
    ]
