# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 04:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cric', '0002_auto_20171020_0833'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aus',
            new_name='Australia',
        ),
        migrations.AlterModelOptions(
            name='australia',
            options={'verbose_name_plural': 'Australians'},
        ),
        migrations.AlterModelOptions(
            name='england',
            options={'verbose_name_plural': "England's"},
        ),
        migrations.AlterModelOptions(
            name='india',
            options={'verbose_name_plural': 'Indians'},
        ),
        migrations.AlterModelOptions(
            name='south_africa',
            options={'verbose_name_plural': 'South_Africans'},
        ),
    ]
