# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cric', '0003_auto_20171020_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='australia',
            options={'ordering': ['Date_of_Publishing'], 'verbose_name_plural': 'Australians'},
        ),
        migrations.AlterModelOptions(
            name='england',
            options={'ordering': ['Date_of_Publishing'], 'verbose_name_plural': "England's"},
        ),
        migrations.AlterModelOptions(
            name='india',
            options={'ordering': ['Date_of_Publishing'], 'verbose_name_plural': 'Indians'},
        ),
        migrations.AlterModelOptions(
            name='south_africa',
            options={'ordering': ['Date_of_Publishing'], 'verbose_name_plural': 'South_Africans'},
        ),
        migrations.AlterField(
            model_name='australia',
            name='Date_of_Publishing',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='england',
            name='Date_of_Publishing',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='india',
            name='Date_of_Publishing',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='south_africa',
            name='Date_of_Publishing',
            field=models.DateTimeField(),
        ),
    ]
